CREATE TABLE [dbo].[SensorInfo](
	[SensorID] [int] NOT NULL,
	[RoomID] [int] NOT NULL,
 CONSTRAINT [PK_SensorInfo] PRIMARY KEY CLUSTERED 
(
	[SensorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SensorInfo]  WITH CHECK ADD  CONSTRAINT [FK_SensorInfo_SensorRooms] FOREIGN KEY([RoomID])
REFERENCES [dbo].[SensorRooms] ([RoomID])
GO

ALTER TABLE [dbo].[SensorInfo] CHECK CONSTRAINT [FK_SensorInfo_SensorRooms]